apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pagamentos
  namespace: producao
  labels:
    app: api-pagamentos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pagamentos
  template:
    metadata:
      labels:
        app: api-pagamentos
    spec:
      containers:
        - name: api-pagamentos
          image: ghcr.io/RafaelOC32/api-pagamentos:v1.0.0
          imagePullPolicy: Always